services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    command: sh -c "composer install && php artisan key:generate && php artisan migrate --force && php artisan passport:install"

  frontend:
    image: node:latest
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run serve

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saudehappy
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
